version: '3.6'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
  www:
    depends_on:
    - db
    image: wordpress:latest
    volumes:
    - ".:/var/www/html/wp-content/plugins/wp-rest-api-smtp-sources"
    ports:
    - 80:80
    - 443:443
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password